name: Deploy Widget to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v2
        with:
            deno-version: v2.x
      - uses: actions/checkout@v4
      - run: deno task widget
      - name: Confirm widget is built
        run: ls -l widget/dist
        
